import type { BrowserRuntime } from '../browser/runtime.js';
import type { ToolCapability, Tool } from './types.js';
import type { UserQuestionService } from '../user-questions/types.js';
import type { CredentialVault } from '../browser/vault.js';

export function createBrowserCapability(runtime: BrowserRuntime, userQuestionService?: UserQuestionService, browserConsoleUrl?: string, browserConsoleToken?: string, vault?: CredentialVault): ToolCapability {
  const parse = (raw: string): Record<string, unknown> => { let value: unknown; try { value = JSON.parse(raw); } catch { throw new Error('BROWSER_ARGUMENTS_INVALID'); } if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('BROWSER_ARGUMENTS_INVALID'); return value as Record<string, unknown>; };
  const stringArg = (args: Record<string, unknown>, key: string): string => { const value = args[key]; if (typeof value !== 'string' || value.length === 0) throw new Error(`BROWSER_ARGUMENT_${key}_INVALID`); return value; };
  const open: Tool = { definition: { name: 'browser_open', description: '打开隔离无头浏览器会话。', parameters: { type: 'object', properties: { sessionId: { type: 'string' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify(await runtime.open(stringArg(args, 'sessionId'))); } };
  const navigate: Tool = { definition: { name: 'browser_navigate', description: '在浏览器会话中导航到网页。禁止 file URL。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, url: { type: 'string' } }, required: ['sessionId', 'url'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify(await runtime.navigate(stringArg(args, 'sessionId'), stringArg(args, 'url'))); } };
  const observe: Tool = { definition: { name: 'browser_observe', description: '读取当前页面状态和有界语义元素引用；密码字段不返回值。', parameters: { type: 'object', properties: { sessionId: { type: 'string' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify({ snapshot: await runtime.snapshot(stringArg(args, 'sessionId')), elements: await runtime.observe(stringArg(args, 'sessionId')) }); } };
  const find: Tool = { definition: { name: 'browser_find', description: '在当前语义页面中查找少量匹配元素。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, query: { type: 'string' }, maxMatches: { type: 'number' } }, required: ['sessionId', 'query'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify({ sessionId: stringArg(args, 'sessionId'), elements: await runtime.find(stringArg(args, 'sessionId'), stringArg(args, 'query'), typeof args.maxMatches === 'number' ? args.maxMatches : 10) }); } };
  const read: Tool = { definition: { name: 'browser_read', description: '读取公开网页的有界正文，默认最多 3500 字符并支持 cursor。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, cursor: { type: 'string' }, maxChars: { type: 'number' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify({ sessionId: stringArg(args, 'sessionId'), ...(await runtime.read(stringArg(args, 'sessionId'), typeof args.cursor === 'string' ? args.cursor : undefined, typeof args.maxChars === 'number' ? args.maxChars : 3500)) }); } };
  const links: Tool = { definition: { name: 'browser_links', description: '读取当前页面有界的链接卡片资源，包含 URL、标题文本和图片 alt；适合动态列表/帖子页面，不读取完整 DOM。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, maxLinks: { type: 'number' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); const handle = runtime.requireHandleForRead(stringArg(args, 'sessionId')); if (!handle.links) throw new Error('BROWSER_LINKS_UNAVAILABLE'); return JSON.stringify({ links: await handle.links(typeof args.maxLinks === 'number' ? args.maxLinks : 30) }); } };
  const refProps = { tabId: { type: 'string' }, documentId: { type: 'string' } };
  const context = (args: Record<string, unknown>) => ({ tabId: stringArg(args, 'tabId'), documentId: stringArg(args, 'documentId') });
  const click: Tool = { definition: { name: 'browser_click', description: '点击当前页面的语义元素引用。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, ref: { type: 'string' }, ...refProps }, required: ['sessionId', 'ref', 'tabId', 'documentId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify(await runtime.click(stringArg(args, 'sessionId'), stringArg(args, 'ref'), context(args))); } };
  const type: Tool = { definition: { name: 'browser_type', description: '向普通文本元素输入内容；不得用于密码、OTP、Token 或安全答案。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, ref: { type: 'string' }, text: { type: 'string' }, ...refProps }, required: ['sessionId', 'ref', 'text', 'tabId', 'documentId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); const ref = stringArg(args, 'ref'); if (/password|passwd|otp|token|secret|验证码/i.test(ref)) throw new Error('BROWSER_SECRET_INPUT_REQUIRES_USER'); return JSON.stringify(await runtime.type(stringArg(args, 'sessionId'), ref, stringArg(args, 'text'), context(args))); } };
  const screenshot: Tool = { definition: { name: 'browser_screenshot', description: '获取当前页面截图供用户或受控观察使用。', parameters: { type: 'object', properties: { sessionId: { type: 'string' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = JSON.parse(raw) as { sessionId: string }; const image = await runtime.screenshot(args.sessionId); return JSON.stringify({ sessionId: args.sessionId, mimeType: 'image/png', bytes: image.byteLength }); } };
  const select: Tool = { definition: { name: 'browser_select', description: '选择普通下拉框选项。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, ref: { type: 'string' }, value: { type: 'string' }, ...refProps }, required: ['sessionId', 'ref', 'value', 'tabId', 'documentId'], additionalProperties: false } }, async execute(raw) { const args = parse(raw); return JSON.stringify(await runtime.select(stringArg(args, 'sessionId'), stringArg(args, 'ref'), stringArg(args, 'value'), context(args))); } };
  const requestCredential: Tool = { definition: { name: 'browser_request_credential', description: '请求用户通过 y/n/other 决定凭据输入。选择 other 后，用户可选择手工输入账号密码，或接管浏览器在提示网址完成登录并输入 enter；秘密只进入 Runtime。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, ref: { type: 'string' }, usernameRef: { type: 'string' }, origin: { type: 'string' }, purpose: { type: 'string' }, label: { type: 'string' }, ...refProps }, required: ['sessionId', 'ref', 'origin', 'purpose', 'tabId', 'documentId'], additionalProperties: false } }, async execute(raw, options) { if (!userQuestionService) throw new Error('BROWSER_USER_QUESTION_UNAVAILABLE'); const args = parse(raw); const sessionId = stringArg(args, 'sessionId'); const choice = await userQuestionService.ask({ questions: [{ id: 'credential', header: '登录凭据', question: `是否为 ${stringArg(args, 'origin')} 提供凭据？`, options: [{ label: 'y', description: '使用已保存凭据' }, { label: 'n', description: '拒绝' }, { label: 'other', description: '其他方式：手工输入账号密码或人工接管' }] }] }, options); const answer = choice.answers[0]; if (answer?.selected.includes('n')) return JSON.stringify({ status: 'USER_REJECTED' }); if (answer?.selected.includes('y')) { if (!vault) return JSON.stringify({ status: 'VAULT_NOT_CONFIGURED' }); if (vault.locked) return JSON.stringify({ status: 'VAULT_LOCKED' }); const origin = stringArg(args, 'origin'); const label = typeof args.label === 'string' && args.label ? args.label : 'main'; const entry = vault.get(origin, label); if (!entry) return JSON.stringify({ status: 'CREDENTIAL_NOT_FOUND' }); if (typeof args.usernameRef === 'string') await runtime.userType ? Promise.reject(new Error('BROWSER_AGENT_USER_API_MISMATCH')) : Promise.resolve(); await runtime.type(sessionId, stringArg(args, 'usernameRef'), entry.username, context(args)); await runtime.typeSecret(sessionId, stringArg(args, 'ref'), entry.password, context(args)); return JSON.stringify({ status: 'filled' }); } if (!answer?.selected.includes('other')) return JSON.stringify({ status: 'MANUAL_INPUT_REQUIRED' }); if (answer.custom) { await runtime.typeSecret(sessionId, stringArg(args, 'ref'), answer.custom, context(args)); return JSON.stringify({ status: 'manual_filled' }); }
    const mode = await userQuestionService.ask({ questions: [{ id: 'credential_mode', header: '输入方式', question: `请为 ${stringArg(args, 'origin')} 选择输入方式。`, options: [{ label: 'manual_input', description: '由 Isla 安全通道收集账号和密码' }, { label: 'user_control', description: '打开网页给你接管输入，完成后输入 enter' }] }] }, options);
    const modeAnswer = mode.answers[0];
    if (modeAnswer?.selected.includes('user_control')) { if (!browserConsoleUrl || !browserConsoleToken) return JSON.stringify({ status: 'browser_console_unavailable' }); const lease = runtime.takeUserControl(sessionId); const done = await userQuestionService.ask({ questions: [{ id: 'credential_control_done', header: '完成网页登录', question: `请打开接管控制台 ${browserConsoleUrl}，认证 Token：${browserConsoleToken}，接管会话 ${sessionId}。目标网页：${stringArg(args, 'origin')}。完成账号、密码、验证码或登录跳转后，在这里输入 enter/选择继续。此 Token 只显示给用户，不进入模型上下文。`, options: [{ label: 'enter', description: '我已完成输入并返回' }, { label: 'stop', description: '停止当前任务' }] }] }, options); if (!done.answers[0]?.selected.includes('enter')) return JSON.stringify({ status: 'user_control_stopped', controlEpoch: lease.controlEpoch }); runtime.releaseUserControl(sessionId, lease.controlEpoch); return JSON.stringify({ status: 'user_control_completed', controlEpoch: lease.controlEpoch }); }
    const manual = await userQuestionService.ask({ questions: [{ id: 'credential_manual', header: '手工输入凭据', question: `请为 ${stringArg(args, 'origin')} 输入账号和密码。账号不会进入模型；密码只会进入 Runtime。`, options: [{ label: 'enter', description: '在下方输入账号和密码' }] }] }, options); const custom = manual.answers[0]?.custom; if (!custom) return JSON.stringify({ status: 'manual_input_required' }); let parsed: unknown; try { parsed = JSON.parse(custom); } catch { return JSON.stringify({ status: 'manual_input_required' }); } const values = parsed as { username?: unknown; password?: unknown }; if (typeof values.password !== 'string' || !values.password) return JSON.stringify({ status: 'manual_input_required' }); if (typeof args.usernameRef === 'string' && typeof values.username === 'string' && values.username) await runtime.type(sessionId, args.usernameRef, values.username, context(args)); await runtime.typeSecret(sessionId, stringArg(args, 'ref'), values.password, context(args)); return JSON.stringify({ status: 'manual_filled' }); } };
  const requestUserControl: Tool = { definition: { name: 'browser_request_user_control', description: '在登录、验证码或需要人工网页操作时暂停 Agent，将浏览器切换为 user_control；用户通过 Browser Console 接管并操作，完成后释放控制权，再在 CLI/Console 确认继续。Agent 在此期间不得操作页面。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, reason: { type: 'string' } }, required: ['sessionId', 'reason'], additionalProperties: false } }, async execute(raw, options) { if (!userQuestionService) throw new Error('BROWSER_USER_QUESTION_UNAVAILABLE'); if (!browserConsoleUrl || !browserConsoleToken) throw new Error('BROWSER_CONSOLE_UNAVAILABLE'); const args = parse(raw); const sessionId = stringArg(args, 'sessionId'); const lease = runtime.takeUserControl(sessionId); const choice = await userQuestionService.ask({ questions: [{ id: 'browser_user_control_complete', header: '网页人工接管', question: `请打开接管控制台 ${browserConsoleUrl}，认证 Token：${browserConsoleToken}，接管会话 ${sessionId} 并完成：${stringArg(args, 'reason')}。完成后输入 enter/选择继续。此 Token 只显示给用户，不进入模型上下文。`, options: [{ label: '继续', description: '我已完成网页操作' }, { label: '停止', description: '停止当前任务' }] }] }, options); const answer = choice.answers[0]; if (!answer?.selected.includes('继续')) return JSON.stringify({ status: 'user_control_stopped', controlEpoch: lease.controlEpoch }); runtime.releaseUserControl(sessionId, lease.controlEpoch); return JSON.stringify({ status: 'user_control_completed', controlEpoch: lease.controlEpoch }); } };
  const wait: Tool = { definition: { name: 'browser_wait', description: '等待页面状态变化，最长 30 秒。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, milliseconds: { type: 'number' } }, required: ['sessionId', 'milliseconds'], additionalProperties: false } }, async execute(raw) { const args = JSON.parse(raw) as { sessionId: string; milliseconds: number }; return JSON.stringify(await runtime.wait(args.sessionId, args.milliseconds)); } };
  const scroll: Tool = { definition: { name: 'browser_scroll', description: '滚动当前页面。', parameters: { type: 'object', properties: { sessionId: { type: 'string' }, deltaY: { type: 'number' } }, required: ['sessionId', 'deltaY'], additionalProperties: false } }, async execute(raw) { const args = JSON.parse(raw) as { sessionId: string; deltaY: number }; return JSON.stringify(await runtime.scroll(args.sessionId, args.deltaY)); } };
  const back: Tool = { definition: { name: 'browser_back', description: '返回上一页。', parameters: { type: 'object', properties: { sessionId: { type: 'string' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = JSON.parse(raw) as { sessionId: string }; return JSON.stringify(await runtime.back(args.sessionId)); } };
  const close: Tool = { definition: { name: 'browser_close', description: '关闭浏览器会话。', parameters: { type: 'object', properties: { sessionId: { type: 'string' } }, required: ['sessionId'], additionalProperties: false } }, async execute(raw) { const args = JSON.parse(raw) as { sessionId: string }; await runtime.close(args.sessionId); return JSON.stringify({ closed: true, sessionId: args.sessionId }); } };
  return { id: 'browser', instructions: '使用浏览器工具时不得索要或提交密码、OTP、Token。用户表达“登录、登录后继续、访问账户内容”等意图时，导航并识别登录表单后必须主动调用 browser_request_credential，不要求用户点名工具；由用户选择 y/n/other。动态列表/帖子页面优先 browser_links 获取有界卡片资源，再用 browser_read 读取正文；搜索必须先观察输入框，输入关键词后重新观察并点击当前有效的搜索按钮，不得凭空编造 CSS/XPath。截图仅供用户通过 Browser Console 查看，不是 Agent Tool 能力。若用户只要求查看或识别登录页且明确不要登录，则只观察并停止。遇到验证码、登录提交或需要人工网页操作时调用 browser_request_user_control，等待用户通过 Browser Console 接管并释放。可用于阅读公开网页、论坛、帖子和视频页面，但不得自动执行发布、评论、点赞、关注或删除。', tools: [open, navigate, observe, find, read, links, click, type, select, requestCredential, requestUserControl, wait, scroll, back, close] };
}
