import type { Message } from '../core/types.js';
import type { ToolCapability } from './types.js';

export function createContextCapability(getMessages: () => readonly Message[]): ToolCapability {
  const parse = (raw: string): Record<string, unknown> => { const value = JSON.parse(raw) as unknown; if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('CONTEXT_ARGUMENTS_INVALID'); return value as Record<string, unknown>; };
  const find = { definition: { name: 'context_find', description: '在被压缩的历史中查找与查询相关的少量片段；不会恢复全部历史。', parameters: { type: 'object', properties: { query: { type: 'string' }, maxMatches: { type: 'number' } }, required: ['query'], additionalProperties: false } }, async execute(raw: string) { const args = parse(raw); const query = typeof args.query === 'string' ? args.query.trim().toLowerCase() : ''; if (!query) throw new Error('CONTEXT_QUERY_REQUIRED'); const limit = Math.min(Math.max(typeof args.maxMatches === 'number' ? args.maxMatches : 5, 1), 10); const terms = query.split(/\s+/).filter(Boolean); const matches = getMessages().flatMap((message, index) => { const text = message.content.toLowerCase(); const score = terms.filter(term => text.includes(term)).length; return score ? [{ sourceId: String(index), role: message.role, score, snippet: message.content.slice(0, 500) }] : []; }).sort((a, b) => b.score - a.score).slice(0, limit); return JSON.stringify({ matches }); } };
  const read = { definition: { name: 'context_read', description: '按 sourceId 有界读取一段历史细节；使用 cursor 分页。', parameters: { type: 'object', properties: { sourceId: { type: 'string' }, cursor: { type: 'number' }, maxChars: { type: 'number' } }, required: ['sourceId'], additionalProperties: false } }, async execute(raw: string) { const args = parse(raw); const index = Number(args.sourceId); const messages = getMessages(); const message = Number.isInteger(index) && index >= 0 ? messages[index] : undefined; if (!message) throw new Error('CONTEXT_SOURCE_NOT_FOUND'); const start = typeof args.cursor === 'number' ? Math.max(0, args.cursor) : 0; const max = Math.min(Math.max(typeof args.maxChars === 'number' ? args.maxChars : 3500, 100), 3500); const text = message.content.slice(start, start + max); return JSON.stringify({ sourceId: String(index), role: message.role, text, ...(start + text.length < message.content.length ? { cursor: start + text.length } : {}) }); } };
  return { id: 'context', instructions: '历史细节默认不进入上下文；只有需要核对过去证据时使用 context_find，再用 context_read 有界读取。不得要求恢复全部历史。', tools: [find, read] };
}
